version: '3'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile-Api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/novelify
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  front:
    build:
      context: .
      dockerfile: Dockerfile-Front
    command: sh -c "yarn start"
    ports:
      - '8080:8080'
    depends_on:
      - web
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - ./front:/front

volumes:
  pgdata:
